[libdefaults]
    default_realm = WESTSIDEUNION.COM
    dns_lookup_realm = false
    dns_lookup_kdc = false
    forwardable = true

[realms]
    WESTSIDEUNION.COM = {
        kdc = 10.44.1.20
        admin_server = 10.44.1.20
    }

[domain_realm]
    .westsideunion.com = WESTSIDEUNION.COM
    westsideunion.com = WESTSIDEUNION.COM
